### ISSUE TITLE
Work on Python library

### ISSUE THREAD

**Issue by brndnln** [vexico/spookvooper-api#2]
Work on Python version

**Tasks:**
- [x] Add first requested items
- [ ] Add /user
- [ ] Add /eco
- [ ] Add /group
- [ ] Add /auth
- [ ] Add premade items
  
- [x] Publish to PyPI

Requested by @ThatKidMellow

**Comment by brendan-lane** [comment]
Fixed spelling and checked off 

- Add first requested items
- Publish to PyPI

**Comment by brndnln** [comment]
Python support dropped.
